server:
  error:
    path: /error
    whitelabel:
      enabled: false
  port: 8080
spring:
  application:
    name: Spring Web Exercise
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
h2:
  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      poolName: SpringBootHikariH2
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
postgresql:
  datasource:
    jdbc-Url: jdbc:postgresql://ec2-107-20-183-142.compute-1.amazonaws.com:5432/d986sp1hs8cc4m?sslmode=require
    username: scvemignetfbdn
    password: d8253d6f12d2d38361fd1e543a8f394f3626cb3bc7ac1fa245aa9e7ee4e19181
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      poolName: SpringBootHikariPostgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #ddl-auto: none
        ddl-auto: create
mysql:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/hibernate_adminSpringMVC?useSSL=false&amp;useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-test-query: SELECT 1
